site_name: Sähkötekniikka
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tabs.annotate
    - content.tabs.copy
  language: fi
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        title: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        title: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


extra: 
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/JonneSaloranta
    - icon: fontawesome/brands/linkedin
      link: https://fi.linkedin.com/in/jonne-saloranta-596555150

copyright: Copyright © 2024 Jonne Saloranta