site_name: Sähkötekniikka
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.tabs.annotate
    - content.tabs.copy
    - content.tooltips
  language: fi
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        title: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        title: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - abbr
  - tables
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - glightbox
  - search

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


extra: 
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/JonneSaloranta
    - icon: fontawesome/brands/linkedin
      link: https://fi.linkedin.com/in/jonne-saloranta-596555150

copyright: Copyright © 2024 Jonne Saloranta